config_version = 12

[audio]
enable_sounds = true

[bar.default]
center = [ "audio_visualizer", "media" ]
end = [ "tray", "notifications", "clipboard", "control-center", "group:g2" ]
margin_edge = 6
margin_ends = 8
radius = 8
start = [ "launcher", "workspaces", "active_window" ]

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "workspaces", "wallpaper" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "battery", "clock" ]
    opacity = 1.0
    padding = 6.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 841.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

[osd]
background_opacity = 0.96999997831881046
offset_y = 20
position = "bottom_center"

[shell]
niri_overview_type_to_launch_enabled = true
polkit_agent = true

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "cava", "gtk3", "ghostty", "niri" ]

[wallpaper]
directory = "/home/vijeth/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/vijeth/Wallpapers/wallpaper-033.png"

    [wallpaper.last]
    path = "/home/vijeth/Wallpapers/wallpaper-033.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/vijeth/Wallpapers/wallpaper-033.png"

[widget.active_window]
capsule = true

[widget.battery]
capsule = true
display_mode = "graphic"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.clipboard]
capsule = true

[widget.clock]
capsule = true
capsule_padding = 8
format = "{:%I:%M%p}"

[widget.control-center]
capsule = true

[widget.launcher]
capsule = true

[widget.media]
capsule = true
hide_when_no_media = true

[widget.notifications]
capsule = true
hide_when_no_unread = true

[widget.session]
capsule = true

[widget.workspaces]
capsule = true
label_source = "name"
